export const buttonData = [
    {id:0, value:"7", type:"button", text:"7"},
    {id:1, value:"8", type:"button", text:"8"},
    {id:2, value:"9", type:"button", text:"9"},
    {id:3, value:"backslash", type:"button", text:"🡄"},
    {id:4, value:"4", type:"button", text:"4"},
    {id:5, value:"5", type:"button", text:"5"},
    {id:6, value:"6", type:"button", text:"6"},
    {id:7, value:"*", type:"button", text:"*"},
    {id:8, value:"1", type:"button", text:"1"},
    {id:9, value:"2", type:"button", text:"2"},
    {id:10, value:"3", type:"button", text:"3"},
    {id:11, value:"+", type:"button", text:"+"},
    {id:12, value:"0", type:"button", text:"0"},
    {id:13, value:"/", type:"button", text:"/"},
    {id:14, value:"-", type:"button", text:"-"},
    {id:15, value:"clear", type:"button", text:"AC"},
    {id:16, value:"=", type:"button", text:"="},
]